# Generated by Django 4.2.2 on 2023-08-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investment", "0003_invest"),
    ]

    operations = [
        migrations.AddField(
            model_name="invest",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="pdfs/"),
        ),
        migrations.AddField(
            model_name="invest",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="invest",
            name="time_to_manage",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="invest",
            name="time_to_reach_goal",
            field=models.IntegerField(),
        ),
    ]
